{application,proper_case,
             [{config_mtime,1772680987},
              {optional_applications,[]},
              {applications,[kernel,stdlib,elixir,logger]},
              {description,"An Elixir library that converts keys in maps between `snake_case` and `camel_case`.\n\nUseful as a plug in Phoenix for converting incoming params from JavaScript's `camelCase` to Elixir's `snake_case`\n"},
              {modules,['Elixir.ProperCase','Elixir.ProperCase.JSONEncoder',
                        'Elixir.ProperCase.JSONEncoder.CamelCase',
                        'Elixir.ProperCase.Plug.SnakeCaseParams']},
              {registered,[]},
              {vsn,"1.3.1"}]}.
